### ISSUE TITLE
No permissions

### ISSUE THREAD

**Issue by MrUnknownGamer** [jkralicky/Screengrab#2]
Hey,

so im in ULX Superadmin and it says i dont have permissions. Help

**Comment by BuilderGaming** [comment]
Also when I don't have permissions, I cant close it. The close button doesn't work and I must restart

**Comment by MrUnknownGamer** [comment]
You here?

**Comment by jkralicky** [comment]
Sorry, I don't support this addon anymore. Feel free to have someone else work on it and send a pull request.
